name: LOCI Upload
description: Upload binary to LOCI
author: AuroraLabs

inputs:
  requirements-file:
    description: Path to requirements.txt
    required: false
    default: requirements.txt
  binary:
    description: Path to elf file
    required: true
  project:
    description: Project name
    required: true
  version:
    description: Version name
    required: true

runs:
  using: composite
  steps:
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install python dependencies
      run: pip install --cache-dir ~/.cache/pip -r ${{ inputs.requirements-file }}
      shell: bash
    - name: Upload binary to LOCI
      run: python -m loci_api upload "${{ inputs.binary }}" "${{ inputs.project }}" "${{ inputs.version }}"
      shell: bash