name: LOCI
description: Line of Code Insights Tool
inputs:
  mode:
    description: Mode to run
    required: true
  requirements-file:
    description: Path to requirements.txt
    required: false
    default: requirements.txt
  binaries:
    description: Paths to binaries to upload
    required: false
  project:
    description: Name of the existing project for which to retrieve function insights
    required: false
  version:
    description: Version of the project for which to retrieve function insights
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/common
      with:
        requirements-file: ${{ inputs.requirements-file }}
    - name: Activate upload mode
      if: ${{ inputs.mode == 'upload' }}
      uses: ./.github/actions/upload
      with:
        project:   ${{ inputs.project }}
        version:   ${{ inputs.version }}
        binaries:  ${{ inputs.binaries }}
    # - name: Activate insights mode
    #   if: ${{ inputs.mode == 'insights' }}
    #   uses: ./.github/actions/insights
    #   with:
    #     project: ${{ inputs.project }}
    #     version: ${{ inputs.version }}
