name: "LOCI Upload"
description: "Upload binary to LOCI"
author: "AuroraLabs"

inputs:
  requirements-file:
    description: "Path to requirements.txt"
    required: false
    default: "requirements.txt"
  elf:
    description: "Path to binary elf"
    required: true

runs:
  using: "composite"
  steps:
    - name: Caching pip
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Installing python dependencies
      run: pip install --cache-dir ~/.cache/pip -r ${{ inputs.requirements-file }}
      shell: bash
    - name: Uploading binary to LOCI
      run: python -m loci_api list-projects
      shell: bash