name: LOCI Function Insights
description: Action that generates function insights of given project
author: AuroraLabs
inputs:
  project:
    description: Name of the existing project for which to retrieve function insights
    required: true
  version:
    description: Version of the project for which to retrieve function insights
    required: true
runs:
  using: composite
  steps:
    - name: Fetch function insights
      run: |
        echo ::group::Get function insights for project's version
        bash -x -c "loci_api func-insights  \
                    ${{ inputs.project }}   \
                    ${{ inputs.version }}"
        echo "Function insights fetched"
        echo ::endgroup::
      shell: bash