name: LOCI Common
description: Action for running common steps
runs:
  using: composite
  steps:
    - name: Use cached dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~\AppData\Local\pip\Cache
        key: '${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}'
        restore-keys: '${{ runner.os }}-pip-'
    - name: Install dependencies
      run: |
          echo ::group::Install python dependencies
          pip install --cache-dir ~/.cache/pip -r ${{ inputs.requirements-file }}
          echo ::endgroup::
      shell: bash