name: LOCI Upload
description: Upload binary to LOCI
author: AuroraLabs
inputs:
  binary:
    description: Path to the ZIP archive containing all binaries to upload
    required: true
  project:
    description: Name of an existing project to associate with this upload
    required: true
  version:
    description: Version identifier for this upload
    required: true
runs:
  using: composite
  steps:
    - name: Upload binary to LOCI
      run: >-
        loci_api upload
        "${{ inputs.binary }}"
        "${{ inputs.project }}"
        "${{ inputs.version }}"
      shell: bash