name: LOCI Upload
description: Upload binary to LOCI
author: AuroraLabs
inputs:
  binaries:
    description: Paths to binaries to upload
    required: true
  project:
    description: Name of an existing project to associate with this upload
    required: true
  version:
    description: Version identifier for this upload
    required: true
runs:
  using: composite
  steps:
    - name: Prepare binaries
      run: |
          while IFS= read -r line; do
            [[ -n "$line" ]] && files+=("$line")
          done <<< "${{ inputs.binaries }}"
          arch_binaries_path="$PWD/binaries.zip"
          zip "$arch_binaries_path" "${files[@]}"
          echo "arch_binaries_path=$arch_binaries_path" >> "$GITHUB_ENV"
      shell: bash
    - name: Upload binary to LOCI
      run: >-
        loci_api upload
        "$arch_binaries_path"
        "${{ inputs.project }}"
        "${{ inputs.version }}"
      shell: bash