name: LOCI Upload
description: Upload new version of binaries to LOCI
author: AuroraLabs
inputs:
  binaries:
    description: Paths to binaries to upload
    required: true
  project:
    description: Name of an existing project to associate with this upload
    required: true
  version:
    description: Version identifier for this upload
    required: true
runs:
  using: composite
  steps:
    - name: Prepare inputs
      run: |
          echo "::group::Collect binaries"
            while IFS= read -r line; do
              [[ -n "$line" ]] && files+=("$line")
            done <<< "${{ inputs.binaries }}"
          echo "::endgroup::"

          echo "::group::Archive binaries" 
            arch_binaries_path="$PWD/binaries.zip"
            zip "$arch_binaries_path" "${files[@]}"
            echo "arch_binaries_path=$arch_binaries_path" >> "$GITHUB_ENV"
          echo "::endgroup::"
      shell: bash
    - name: Upload new project version to LOCI
      run: |
        echo "::group::Upload archived binaries as new project version"
          loci_api upload           \
          "$arch_binaries_path"     \
          "${{ inputs.project }}"   \
          "${{ inputs.version }}"
        echo "::endgroup::"
      shell: bash