name: LOCI Upload
description: Action that uploads new project version to LOCI
author: AuroraLabs
inputs:
  binaries:
    description: Paths to binaries to upload
    required: true
  project:
    description: Name of an existing project to associate with this upload
    required: true
  version:
    description: Version identifier for this upload
    required: true
runs:
  using: composite
  steps:
    - name: Prepare inputs
      run: |
          echo "::group::Collect binaries"
          echo "Collecting binaries"
          set -x
          while IFS= read -r line; do
            [[ -n "$line" ]] && files+=("$line")
          done <<< "${{ inputs.binaries }}"
          set +x
          echo "Binaries collected"
          echo "::endgroup::"

          echo "::group::Archive binaries"
          echo "Archiving binaries"
          set -x
          arch_binaries_path="$PWD/binaries.zip"
          zip "$arch_binaries_path" "${files[@]}"
          echo "arch_binaries_path=$arch_binaries_path" >> "$GITHUB_ENV"
          set +x
          echo "Binaries archived"
          echo "::endgroup::"

          file  "$arch_binaries_path"
          ls -l "$arch_binaries_path"
      shell: bash
    # - name: Upload new project version to LOCI
    #   run: |
    #
    #     echo "::group::Upload archived binaries as new project version"
    #       loci_api upload           \
    #       "$arch_binaries_path"     \
    #       "${{ inputs.project }}"   \
    #       "${{ inputs.version }}"
    #     echo "::endgroup::"
    #   shell: bash