name: GitHub Demo Build Workflow
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: 
      - main

env:
  LOCI_PROJECT: GHDemo

jobs:
  build-and-upload:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          echo "Cross compiler installed"
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build sample
        run: |
          mkdir -p build
          aarch64-linux-gnu-g++ -o "build/sample_01" \
          samples/sample_01.cpp
          echo "Successfully compiled build/sample_01"
        shell: bash
