name: Example action
'on':
  push:
  workflow_dispatch:
jobs:
  loci:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          echo "commands"
          echo ::group::Install AArch64 cross-compiler
          echo "Installing aarch64 compiler packages"
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          echo "Cross compiler installed"
          echo ::endgroup::
      # - name: Checkout repository
      #   uses: actions/checkout@v4
      - name: Build binaries
        run: |
          echo "commands"
          echo ::group::Compile example version 1
          echo "Compiling example/case_01 (version 1)"
          mkdir -p build/bin
          aarch64-linux-gnu-g++ -o "build/bin/case_01 v1" \
          examples/case_01/test_01.cpp
          echo "Compiled example/case_01 (version 1)"
          echo ::endgroup::
          echo ::group::Compile example version 2
          echo "Compiling example/case_01 (version 2)"
          aarch64-linux-gnu-g++ -o "build/bin/case_01 v2" \
          examples/case_01/test_02.cpp
          echo "Compiled example/case_01 (version 2)"
          echo ::endgroup::
      - name: Run LOCI Upload
        uses: ./
        env:
          LOCI_BACKEND_URL: '${{ secrets.LOCI_BACKEND_URL }}'
          LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
        with:
          mode: upload
          binaries: |
                ./build/bin/case_01 v1
                ./build/bin/case_01 v2
          project: DIFF Tests
          version: case_03_v1
      
      - name: Run LOCI Insights
        uses: ./
        env:
          LOCI_BACKEND_URL: '${{ secrets.LOCI_BACKEND_URL }}'
          LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
        with:
          mode: insights
          project: DIFF Tests
          version: case_03_v1
