name: Example action
'on':
  push:
  workflow_dispatch:
jobs:
  loci:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          echo ::group::Install AArch64 cross-compiler
          echo "Installing aarch64 compiler packages"
          bash -x -c "sudo apt-get update"
          bash -x -c "sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu"
          echo "Cross compiler installed"
          echo ::endgroup::
        shell: bash
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compile example version 1
        run: |
          mkdir -p build/bin
          aarch64-linux-gnu-g++ -o "build/bin/case_01 v1" \
          examples/case_01/test_01.cpp
          echo "Successfully compiled example/case_01 (version 1)"
        shell: bash
      - name: Compile example version 2
        run: |
            aarch64-linux-gnu-g++ -o "build/bin/case_01 v2" \
            examples/case_01/test_02.cpp
            echo "Successfully compiled example/case_01 (version 2)"
        shell: bash
      - name: Upload binaries (loci)
        uses: ./
        env:
          LOCI_BACKEND_URL: '${{ secrets.LOCI_BACKEND_URL }}'
          LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
        with:
          mode: upload
          binaries: |
                ./build/bin/case_01 v1
                ./build/bin/case_01 v2
          project: DIFF Tests
          version: case_03_v1
      
      - name: Fetch function insights (loci)
        uses: ./
        env:
          LOCI_BACKEND_URL: '${{ secrets.LOCI_BACKEND_URL }}'
          LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
        with:
          mode: insights
          project: DIFF Tests
          version: case_03_v1
