name: 'Test action'

on:
    push: 
    workflow_dispatch:

jobs:
    loci-upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Compile c++ code
              run: |
                mkdir build
                g++ -o build/test test.cpp
                ls -lh ./build/test

            - name: Run my composite action
              uses: ./
              env:
                LOCI_BACKEND_URL: ${{ secrets.LOCI_BACKEND_URL }}
                LOCI_API_KEY: ${{ secrets.LOCI_API_KEY }}                        
              with:
                elf: ./build/test